<div class="row">
    <div class="col-12">
        <?php
        $foro->Seleccionar("id = $id_foro");
        if ($foro->TotalFilasConsulta() > 0) {
            for ($i = 0; $i < $foro->TotalFilasConsulta(); $i++) {
                $foro->CargarDatos($i);
                echo '<div class="row bg-white align-items-center mx-1 p-4">
                        <div class="col-2">
                            <a href="index.php?controller=foro&action=comentario&id=' . $foro->getId() . '">
                                <img src="View/Public_html/Imagenes/logo.png" alt="" class="img-fluid">
                            </a>
                        </div>
                        <div class="col-10">
                            <a class="display-4 text-break text-decoration-none" href="index.php?controller=foro&action=comentario&id=' . $foro->getId() . '">' . $foro->getTitulo() . '</a>
                        </div>
                    </div>';
                echo '<div class="row bg-white align-items-center justify-content-center mx-1">
                        <div class="col-8 media-body">
                            <p class="text-justify">' . $foro->getDescripcion() . '</p>
                        </div>
                    </div>';
            }
        } else {
            echo "<h1>Lo siento no tenemos ese tema en el foro actualmente</h1>";
        }

        $foro->SeleccionarComentarios("id_foro = $id_foro");
        if ($foro->TotalFilasConsulta() > 0) {
            for ($i = 0; $i < $foro->TotalFilasConsulta(); $i++) {
                $foro->CargarComentarios($i);
                $usuario = new Login($enlaceBD);
                $idUsuario = $foro->getId_usuario();
                $usuario->Seleccionar("id = $idUsuario");
                $usuario->CargarDatos(0);
                echo '<div class="col-12 bg-white mt-3 media">
                <div class="row align-items-center">
                    <div class="col-3">
                        <img src="View/Public_html/Imagenes/' . $usuario->getFoto() . '" alt="" class="img-fluid">
                        <p class="text-center">' . $usuario->getNombre_usuario() . '</p>
                    </div>
                    <div class="col-9">
                        <p>' . $foro->getMensaje() . '</p>
                    </div>
                </div>
            </div>';
            }
        } else {
            echo "<h1 class='text-white text-center'>Se el primero en comentar este tema del foro ;)</h1>";
        }
        ?>
    </div>
    <div class="col-12">
        <form class="form-inline mx-3 row" action="#" method="post">
            <input class="form-control col-10" type="text" name="comentario_usuario" id="">
            <button class="btn col-2" type="submit"><img src="View/Public_html/Imagenes/flechaEnvio.png" alt="" class="img-fluid"></button>
        </form>
    </div>

</div>