<div class="row mx-2">
    <div class="col-12 text-center bg-white p-2">
        <h1 class="display-2 d-none d-md-block">TEMAS DEL FORO</h1>
        <h1 class="d-block d-md-none">TEMAS DEL FORO</h1>
    </div>
    <div class="col-12">
        <?php
            if($foro->TotalFilasConsulta()>0){
                for ($i=0; $i < $foro->TotalFilasConsulta(); $i++) { 
                    $foro->CargarDatos($i);
                    echo '<div class="row bg-white align-items-center p-4">
                        <div class="col-2">
                            <a href="index.php?controller=foro&action=comentario&id=' . $foro->getId() . '">
                                <img src="View/Public_html/Imagenes/logo.png" alt="" class="img-fluid d-none d-md-block">
                                <img src="View/Public_html/Imagenes/logo.png" alt="" class="img-fluid d-block d-md-none w-100">
                            </a>
                        </div>
                        <div class="col-10">
                            <h5 class="d-block d-md-none"><a class="text-decoration-none" href="index.php?controller=foro&action=comentario&id=' . $foro->getId() . '">' . $foro->getTitulo() . '</a></h5>
                            <a class="display-4 d-none d-md-block text-decoration-none" href="index.php?controller=foro&action=comentario&id=' . $foro->getId() . '">' . $foro->getTitulo() . '</a>
                        </div>
                    </div>';
                }
            }else{
                echo "<h1>Lo siento no tenemos temas en el foro actualmente</h1>";
            }
        ?>
    </div>
</div>
<div class="text-center">
    <p class="text-white">Páginas:</p>
        <?php
            for ($i=1; $i <= $total_paginas; $i++) { 
                echo " <a class='text-white text-center' href='index.php?controller=foro&action=index&pagina=" . $i . "'><b>" . $i . "</b></a>&nbsp;";
            }
        ?>
</div>