<div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-3 login rounded m-5 p-5">
        <form class="form text-center" action="index.php?logeado" method="post">
            <div class="form-group">
                <label class="font-weight-bold" for="usario">Usuario:</label>
                <input class="form-control" type="text" name="usuario" id="" required>
            </div>
            <div class="form-group">
                <label class="font-weight-bold" for="pass">Contraseña:</label>
                <input class="form-control" type="password" name="pass" id="" required>
            </div>
            <button class="btn m-3" type="submit">Entrar</button>
            <a class="btn m-3" href="index.php?controller=login&action=registro">Registrarse</a>
        </form>
    </div>
</div>