<div class="row justify-content-center">
    <div class="col-12 col-md-6 col-lg-3 login rounded m-5 p-5">
        <form class="form text-center" action="index.php?registrado" method="post">
            <div class="form-group">
                <label class="font-weight-bold" for="usario">Usuario:</label>
                <input class="form-control" type="text" name="usuario" id="usuario" required>
            </div>
            <div class="form-group">
                <label class="font-weight-bold" for="pass">Contraseña:</label>
                <input class="form-control" type="password" name="pass" id="pass" required>
            </div>
            <div class="form-group">
                <label class="font-weight-bold" for="email">Email:</label>
                <input class="form-control" type="email" name="email" id="email" required>
            </div>
            <button class="btn" type="submit">Registrarse</button>
        </form>
    </div>
</div>