<div class="row justify-content-center aling-items-center juegos">
    <div class="col-12 col-md-5 m-2 plataforma">
        <div class="card">
            <a href="index.php?controller=juego&action=index&plataforma=1">
                <img src="View/Public_html/Imagenes/play.jpg" alt="" class="card-img-top img-fluid">
            </a>
            <div class="card-body">
                <h4 class="card-title text-center">
                    PLAYSTATION
                </h4>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-5 m-2 plataforma">
        <div class="card">
            <a href="index.php?controller=juego&action=index&plataforma=4">
                <img src="View/Public_html/Imagenes/Nintendo.jpg" alt="" class="card-img-top img-fluid">
            </a>
            <div class="card-body">
                <h4 class="card-title text-center">
                    NINTENDO
                </h4>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-5 m-2 plataforma">
        <div class="card">
            <a href="index.php?controller=juego&action=index&plataforma=2">
                <img src="View/Public_html/Imagenes/xbox.jpg" alt="" class="card-img-top img-fluid">
            </a>
            <div class="card-body">
                <h4 class="card-title text-center">
                    XBOX
                </h4>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-5 m-2 plataforma">
        <div class="card">
            <a href="index.php?controller=juego&action=index&plataforma=3">
                <img src="View/Public_html/Imagenes/PC.jpg" alt="" class="card-img-top img-fluid">
            </a>
            <div class="card-body">
                <h4 class="card-title text-center">
                    PC
                </h4>
            </div>
        </div>
    </div>
</div>