<div class="row">
    <div class="col-12">
        <img src="View/Public_html/Imagenes/gamer_imagen.jpg" alt="" class="img-fluid w-100">
        <?php
        if ($noticias->TotalFilasConsulta() > 0) {
            for ($i = 0; $i < $noticias->TotalFilasConsulta(); $i++) {
                $noticias->CargarDatos($i);
                echo '<div class="row align-items-center justify-content-center bg-white p-5 mx-1 my-3">
                        <a href="index.php?controller=portada&action=noticia&nombre_noticia=' . $noticias->getNombre_noticia() . '" class="col-12 col-md-5 text-center">
                            <img src="View/Public_html/Imagenes/' . $noticias->getFoto() . '" alt="" class="img-fluid">
                        </a>
                        <div class="col-12 col-md-7 text-center">
                            <h2 class="titulo">' . $noticias->getNombre_noticia() . '</h2>
                            <p class="text-nowrap text-truncate desc_corta">' . $noticias->getDesc_noticia() . '</p>
                        </div>
                    </div>';
            }
            echo '<div class="text-center">
                    <p class="text-white text-center">Páginas:&nbsp;</p>';
            for ($i = 1; $i <= $total_paginas; $i++) {
                echo " <a class='text-white text-center' href='index.php?controller=portada&action=index&pagina=" . $i . "'>" . $i . "</a>&nbsp;";
            }
            echo "</div>";
        }
        if ($noticias->TotalFilasConsulta() == 0) {
            echo "<h1>Lo siento, pero actualmente no tenemos noticias</h1>";
        }
        ?>

    </div>
</div>