<div class="row no-gutters">
    <div class="col-12 text-center text-white p-2">
        <h1 class="display-4">GESTIÓN DE USUARIOS DEL ADMINISTRADOR</h1>
    </div>
    <div class="col-12 pt-2 list-group">
        <?php
            if($usuario->TotalFilasConsulta()>0){
                for ($i=0; $i < $usuario->TotalFilasConsulta(); $i++) { 
                    $usuario->CargarDatos($i);
                    echo '<div class="row pt-5 align-items-center justify-content-around mx-3">
                    <p class="col-12 text-center list-group-item list-group-item-action">'.$usuario->getNombre_usuario().'</p>
                    <a href="index.php?controller=admin&action=ver&nombre='.$usuario->getNombre_usuario().'" class="col-3 btn btn-primary">Ver</a>
                    <a href="index.php?controller=admin&action=eliminar&nombre='.$usuario->getNombre_usuario().'" class="col-3 btn btn-warning">Eliminar</a>
                    </div>';
                }
            }else{
                echo "<h1>Lo siento no existen usuarios en este foro registrados</h1>";
            }
        ?>
    </div>
</div>
<div class="text-center">
    <p class="text-white">Páginas:</p>
        <?php
            for ($i=1; $i <= $total_paginas; $i++) { 
                echo " <a class='text-white text-center' href='index.php?controller=admin&action=index&pagina=" . $i . "'><b>" . $i . "</b></a>&nbsp;";
            }
        ?>
</div>